### ISSUE TITLE
Custom location of config file?

### ISSUE THREAD

**Issue by pat-s** [tfeldmann/organize#14]
Is there an easy way to set a custom location of the config file? Would like to store in in the cloud to have it synced.

**Comment by tfeldmann** [comment]
No, at the moment this is not possible. You can symlink the config file to some cloud-synced folder as a workaround. I added it to the todo list!

**Comment by dskaggs** [comment]
@pat-s I run Organize inside a Docker container that I created (https://hub.docker.com/r/dskaggs/docker-organize). I map the config file location to a volume in the Docker container so that I can keep it on my local machine and rebuild the Docker container as many times as I'd like without losing my config. Example in the README.

**Comment by pat-s** [comment]
Thanks for the suggestion. I now use [mackup](https://github.com/lra/mackup) to sync all my config files.

**Comment by tfeldmann** [comment]
Just wanted to let you know that custom config file locations are now possible using either the ``--config-file`` command line argument or the ``$ORGANIZE_CONFIG`` env variable 👍
